### ISSUE TITLE
Not working in sketch 67

### ISSUE THREAD

**Issue by michelve** [ukn530/FontFinder#18]
Not working in sketch 67

**Comment by michelve** [comment]
I update line 5-7 to this in ~/Library/Application Support/com.bohemiancoding.sketch3/Plugins/FontFinder.sketchplugin/Contents/Sketch/findFontName.cocoascript to this:

```    // CRAZY CODE: confusing how to use context
    // This 3 lines use just for deselect layers
    // but I should use these for all of code
    var document = require('sketch/dom').selectedDocument;
    var selection = require('sketch/dom').selectedLayers;

    var doc = context.document; ```

**Comment by dezinerd** [comment]
Not working on Sketch 68.1

Console showing this on action: 
```
TypeError: context.api is not a function. (In 'context.api()', 'context.api' is null)
    at onRun (/Users/dominic.haberstumpf/Library/Application Support/com.bohemiancoding.sketch3/Plugins/FontFinder.sketchplugin/Contents/Sketch/findFontName.cocoascript:6:29)
```

**Comment by dezinerd** [comment]
Not working on Sketch 68.1

Console showing this when running plugin:

```
TypeError: context.api is not a function. (In 'context.api()', 'context.api' is null)
    at onRun (/Users/'user'/Library/Application Support/com.bohemiancoding.sketch3/Plugins/FontFinder.sketchplugin/Contents/Sketch/findFontName.cocoascript:6:29)
```
