### ISSUE TITLE
Sketch 68 Iissue

### ISSUE THREAD

**Issue by dezinerd** [ukn530/FontFinder#19]
Not working on Sketch 68.1

Console showing this when running plugin:

```
TypeError: context.api is not a function. (In 'context.api()', 'context.api' is null)
    at onRun (/Users/'user'/Library/Application Support/com.bohemiancoding.sketch3/Plugins/FontFinder.sketchplugin/Contents/Sketch/findFontName.cocoascript:6:29)
```
